Merged PROACTIVE-685 from trunk@12906
PROACTIVE-685
catch Throwable instead of Exception in order to be able to print the stack when the generation failed for instance with a java.lang.NoClassDefFoundError


Conflicts:

	src/Core/org/objectweb/proactive/ext/util/StubGenerator.java

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/proactive/branches/ProActive_4.1.x@13042 28e8926c-6b08-0410-baaa-805c5e19b8d6