Prevent java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()
Issue and solutions are well explained at [1].

[1] https://gist.github.com/AlainODea/1375759b8720a3f9f094
(cherry picked from commit c6ac36b)