PROACTIVE-685 catch Throwable instead of Exception in order to be able to print the stack when the generation failed for instance with a java.lang.NoClassDefFoundError
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/proactive/trunk@12906 28e8926c-6b08-0410-baaa-805c5e19b8d6